[2021-06-25 09:18:44,173] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-03-08T00:00:00+00:00 [queued]>
[2021-06-25 09:18:44,568] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-03-08T00:00:00+00:00 [queued]>
[2021-06-25 09:18:44,569] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 09:18:44,569] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-25 09:18:44,579] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 09:18:44,742] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-03-08T00:00:00+00:00
[2021-06-25 09:18:44,814] {standard_task_runner.py:52} INFO - Started process 7128 to run task
[2021-06-25 09:18:44,890] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-03-08T00:00:00+00:00', '--job-id', '273', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp06dukp3i', '--error-file', '/tmp/tmpton_bn3e']
[2021-06-25 09:18:44,925] {standard_task_runner.py:77} INFO - Job 273: Subtask task_1
[2021-06-25 09:18:45,618] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-03-08T00:00:00+00:00 [running]> on host airflowvm
[2021-06-25 09:18:46,071] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-03-08T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-08T00:00:00+00:00
[2021-06-25 09:18:46,072] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-25 09:18:46,074] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-06-25 09:18:46,167] {subprocess.py:75} INFO - Output:
[2021-06-25 09:18:49,175] {subprocess.py:83} INFO - Command exited with return code 0
[2021-06-25 09:18:49,536] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200308T000000, start_date=20210625T091844, end_date=20210625T091849
[2021-06-25 09:18:50,061] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-06-25 09:18:50,117] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 7128
[2021-06-25 09:18:50,128] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-06-25 09:18:50,128] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-06-25 09:18:50,231] {process_utils.py:66} INFO - Process psutil.Process(pid=7128, status='terminated', exitcode=1, started='09:18:43') (7128) terminated with exit code 1
