[2021-06-25 09:18:33,539] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2020-03-04T00:00:00+00:00 [queued]>
[2021-06-25 09:18:33,747] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2020-03-04T00:00:00+00:00 [queued]>
[2021-06-25 09:18:33,754] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 09:18:33,755] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-25 09:18:33,756] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 09:18:33,828] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_2> on 2020-03-04T00:00:00+00:00
[2021-06-25 09:18:33,843] {standard_task_runner.py:52} INFO - Started process 6829 to run task
[2021-06-25 09:18:33,903] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', '2020-03-04T00:00:00+00:00', '--job-id', '264', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmp91cjmups', '--error-file', '/tmp/tmp58gy6q0q']
[2021-06-25 09:18:33,911] {standard_task_runner.py:77} INFO - Job 264: Subtask task_2
[2021-06-25 09:18:34,249] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_2 2020-03-04T00:00:00+00:00 [running]> on host airflowvm
[2021-06-25 09:18:35,188] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2020-03-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-04T00:00:00+00:00
[2021-06-25 09:18:35,195] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-25 09:18:35,197] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-06-25 09:18:35,263] {subprocess.py:75} INFO - Output:
[2021-06-25 09:18:38,318] {subprocess.py:83} INFO - Command exited with return code 0
[2021-06-25 09:18:38,566] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20200304T000000, start_date=20210625T091833, end_date=20210625T091838
[2021-06-25 09:18:39,205] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-06-25 09:18:39,304] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-06-25 09:18:39,328] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 6829
[2021-06-25 09:18:39,458] {process_utils.py:66} INFO - Process psutil.Process(pid=6829, status='terminated', exitcode=0, started='09:18:32') (6829) terminated with exit code 0
