[2021-06-24 17:07:19,321] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-02-10T00:00:00+00:00 [queued]>
[2021-06-24 17:07:19,449] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-02-10T00:00:00+00:00 [queued]>
[2021-06-24 17:07:19,450] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-24 17:07:19,450] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-24 17:07:19,450] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-24 17:07:19,550] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2020-02-10T00:00:00+00:00
[2021-06-24 17:07:19,585] {standard_task_runner.py:52} INFO - Started process 14067 to run task
[2021-06-24 17:07:19,665] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2020-02-10T00:00:00+00:00', '--job-id', '162', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpuuz2yf2l', '--error-file', '/tmp/tmp4jrkbanz']
[2021-06-24 17:07:19,709] {standard_task_runner.py:77} INFO - Job 162: Subtask task_3
[2021-06-24 17:07:20,283] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2020-02-10T00:00:00+00:00 [running]> on host airflowvm
[2021-06-24 17:07:21,113] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2020-02-10T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-10T00:00:00+00:00
[2021-06-24 17:07:21,140] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-24 17:07:21,194] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-06-24 17:07:21,380] {subprocess.py:75} INFO - Output:
[2021-06-24 17:07:24,478] {subprocess.py:83} INFO - Command exited with return code 0
[2021-06-24 17:07:24,730] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20200210T000000, start_date=20210624T170719, end_date=20210624T170724
[2021-06-24 17:07:24,996] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-06-24 17:07:25,118] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 14067
[2021-06-24 17:07:25,170] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-06-24 17:07:25,170] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-06-24 17:07:25,285] {process_utils.py:66} INFO - Process psutil.Process(pid=14067, status='terminated', exitcode=1, started='17:07:18') (14067) terminated with exit code 1
