[2021-07-01 16:32:14,364] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: get_data_patient.users_treatment 2021-07-01T14:24:03.261240+00:00 [queued]>
[2021-07-01 16:32:14,379] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: get_data_patient.users_treatment 2021-07-01T14:24:03.261240+00:00 [queued]>
[2021-07-01 16:32:14,380] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-07-01 16:32:14,380] {taskinstance.py:1068} INFO - Starting attempt 11 of 11
[2021-07-01 16:32:14,380] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-07-01 16:32:14,410] {taskinstance.py:1087} INFO - Executing <Task(PythonOperator): users_treatment> on 2021-07-01T14:24:03.261240+00:00
[2021-07-01 16:32:14,417] {standard_task_runner.py:52} INFO - Started process 24267 to run task
[2021-07-01 16:32:14,425] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'get_data_patient', 'users_treatment', '2021-07-01T14:24:03.261240+00:00', '--job-id', '994', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/get_Data_Patient.py', '--cfg-path', '/tmp/tmpis7zizvx', '--error-file', '/tmp/tmpe658fjjx']
[2021-07-01 16:32:14,427] {standard_task_runner.py:77} INFO - Job 994: Subtask users_treatment
[2021-07-01 16:32:14,537] {logging_mixin.py:104} INFO - Running <TaskInstance: get_data_patient.users_treatment 2021-07-01T14:24:03.261240+00:00 [running]> on host airflowvm
[2021-07-01 16:32:14,651] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_data_patient
AIRFLOW_CTX_TASK_ID=users_treatment
AIRFLOW_CTX_EXECUTION_DATE=2021-07-01T14:24:03.261240+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-01T14:24:03.261240+00:00
[2021-07-01 16:32:14,669] {logging_mixin.py:104} INFO - " "
[2021-07-01 16:32:14,670] {logging_mixin.py:104} INFO - Users:
[2021-07-01 16:32:14,670] {python.py:151} INFO - Done. Returned value was: None
[2021-07-01 16:32:14,693] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=get_data_patient, task_id=users_treatment, execution_date=20210701T142403, start_date=20210701T163214, end_date=20210701T163214
[2021-07-01 16:32:14,741] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-07-01 16:32:14,767] {local_task_job.py:151} INFO - Task exited with return code 0
