[2021-06-30 14:59:12,472] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing_v2.is_api_available 2021-06-30T14:29:12.044488+00:00 [queued]>
[2021-06-30 14:59:12,533] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing_v2.is_api_available 2021-06-30T14:29:12.044488+00:00 [queued]>
[2021-06-30 14:59:12,533] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-30 14:59:12,533] {taskinstance.py:1068} INFO - Starting attempt 5 of 5
[2021-06-30 14:59:12,534] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-30 14:59:12,567] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-06-30T14:29:12.044488+00:00
[2021-06-30 14:59:12,580] {standard_task_runner.py:52} INFO - Started process 8765 to run task
[2021-06-30 14:59:12,589] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing_v2', 'is_api_available', '2021-06-30T14:29:12.044488+00:00', '--job-id', '876', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing_v2.py', '--cfg-path', '/tmp/tmped6icxn1', '--error-file', '/tmp/tmplzb3m_25']
[2021-06-30 14:59:12,591] {standard_task_runner.py:77} INFO - Job 876: Subtask is_api_available
[2021-06-30 14:59:12,778] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing_v2.is_api_available 2021-06-30T14:29:12.044488+00:00 [running]> on host airflowvm
[2021-06-30 14:59:12,994] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing_v2
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-06-30T14:29:12.044488+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-06-30T14:29:12.044488+00:00
[2021-06-30 14:59:12,995] {http.py:101} INFO - Poking: api/
[2021-06-30 14:59:13,016] {base.py:69} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-06-30 14:59:13,019] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2021-06-30 14:59:13,511] {base.py:243} INFO - Success criteria met. Exiting.
[2021-06-30 14:59:13,528] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing_v2, task_id=is_api_available, execution_date=20210630T142912, start_date=20210630T145912, end_date=20210630T145913
[2021-06-30 14:59:13,596] {taskinstance.py:1245} INFO - 5 downstream tasks scheduled from follow-on schedule check
[2021-06-30 14:59:13,641] {local_task_job.py:151} INFO - Task exited with return code 0
