[2021-06-25 09:44:44,475] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-01-09T00:00:00+00:00 [queued]>
[2021-06-25 09:44:44,849] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2020-01-09T00:00:00+00:00 [queued]>
[2021-06-25 09:44:44,850] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 09:44:44,850] {taskinstance.py:1068} INFO - Starting attempt 2 of 2
[2021-06-25 09:44:44,851] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 09:44:45,057] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2020-01-09T00:00:00+00:00
[2021-06-25 09:44:45,109] {standard_task_runner.py:52} INFO - Started process 18286 to run task
[2021-06-25 09:44:45,157] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2020-01-09T00:00:00+00:00', '--job-id', '374', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpgpgok_pu', '--error-file', '/tmp/tmp5gd3br17']
[2021-06-25 09:44:45,159] {standard_task_runner.py:77} INFO - Job 374: Subtask task_1
[2021-06-25 09:44:46,130] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2020-01-09T00:00:00+00:00 [running]> on host airflowvm
[2021-06-25 09:44:47,498] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2020-01-09T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-09T00:00:00+00:00
[2021-06-25 09:44:47,578] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-25 09:44:47,646] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-06-25 09:44:47,847] {subprocess.py:75} INFO - Output:
[2021-06-25 09:44:50,927] {subprocess.py:83} INFO - Command exited with return code 0
[2021-06-25 09:44:52,214] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20200109T000000, start_date=20210625T094444, end_date=20210625T094452
[2021-06-25 09:44:57,285] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-06-25 09:44:58,172] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 18286
[2021-06-25 09:44:58,486] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-06-25 09:44:58,487] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-06-25 09:44:58,732] {process_utils.py:66} INFO - Process psutil.Process(pid=18286, status='terminated', exitcode=1, started='09:44:44') (18286) terminated with exit code 1
