[2021-06-25 09:17:37,406] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-02-19T00:00:00+00:00 [queued]>
[2021-06-25 09:17:37,796] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-02-19T00:00:00+00:00 [queued]>
[2021-06-25 09:17:37,797] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 09:17:37,797] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-25 09:17:37,798] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 09:17:37,929] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2020-02-19T00:00:00+00:00
[2021-06-25 09:17:37,963] {standard_task_runner.py:52} INFO - Started process 5215 to run task
[2021-06-25 09:17:38,011] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2020-02-19T00:00:00+00:00', '--job-id', '218', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpep56eyn_', '--error-file', '/tmp/tmpwhtzg8iq']
[2021-06-25 09:17:38,054] {standard_task_runner.py:77} INFO - Job 218: Subtask task_3
[2021-06-25 09:17:38,817] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2020-02-19T00:00:00+00:00 [running]> on host airflowvm
[2021-06-25 09:17:39,567] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2020-02-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-02-19T00:00:00+00:00
[2021-06-25 09:17:39,571] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-25 09:17:39,606] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-06-25 09:17:39,753] {subprocess.py:75} INFO - Output:
[2021-06-25 09:17:42,760] {subprocess.py:83} INFO - Command exited with return code 0
[2021-06-25 09:17:43,110] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20200219T000000, start_date=20210625T091737, end_date=20210625T091743
[2021-06-25 09:17:43,490] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-06-25 09:17:43,671] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-06-25 09:17:43,668] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 5215
[2021-06-25 09:17:43,894] {process_utils.py:66} INFO - Process psutil.Process(pid=5215, status='terminated', exitcode=0, started='09:17:37') (5215) terminated with exit code 0
