[2021-06-25 09:18:53,989] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-03-07T00:00:00+00:00 [queued]>
[2021-06-25 09:18:54,425] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2020-03-07T00:00:00+00:00 [queued]>
[2021-06-25 09:18:54,426] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 09:18:54,426] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-06-25 09:18:54,426] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-06-25 09:18:54,653] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2020-03-07T00:00:00+00:00
[2021-06-25 09:18:54,738] {standard_task_runner.py:52} INFO - Started process 7429 to run task
[2021-06-25 09:18:54,851] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2020-03-07T00:00:00+00:00', '--job-id', '281', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_dag.py', '--cfg-path', '/tmp/tmpvsh8r_jk', '--error-file', '/tmp/tmpjkdx19pm']
[2021-06-25 09:18:54,865] {standard_task_runner.py:77} INFO - Job 281: Subtask task_3
[2021-06-25 09:18:55,489] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2020-03-07T00:00:00+00:00 [running]> on host airflowvm
[2021-06-25 09:18:56,071] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2020-03-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-03-07T00:00:00+00:00
[2021-06-25 09:18:56,084] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-06-25 09:18:56,103] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2021-06-25 09:18:56,261] {subprocess.py:75} INFO - Output:
[2021-06-25 09:18:59,330] {subprocess.py:83} INFO - Command exited with return code 0
[2021-06-25 09:18:59,601] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20200307T000000, start_date=20210625T091853, end_date=20210625T091859
[2021-06-25 09:19:00,132] {local_task_job.py:196} WARNING - State of this instance has been externally set to success. Terminating instance.
[2021-06-25 09:19:00,199] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 7429
[2021-06-25 09:19:00,747] {taskinstance.py:1264} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-06-25 09:19:00,748] {subprocess.py:89} INFO - Sending SIGTERM signal to process group
[2021-06-25 09:19:00,828] {process_utils.py:66} INFO - Process psutil.Process(pid=7429, status='terminated', exitcode=1, started='09:18:53') (7429) terminated with exit code 1
